# version: '3.8'

# networks:
#   myapp:
#     driver: bridge

# # docker run --name mysql -d     -p 3306:3306     -e MYSQL_ROOT_PASSWORD=password     --restart unless-stopped    mysql:8
# services:
#   myapp:
#     depends_on:
#       - db    
#     image: web-stack
#     restart: always
#     environment:
#       - DB_DRIVER=mysql
#       - DB_USER=user
#       - DB_PASS=password
#       - DB_NAME=book_example
#       - DB_HOST=0.0.0.0
#       - DB_PORT=3306
#     ports:
#       - '9000:9000'
#     links:
#       - db
#     networks: 
#       - myapp

#   db:
#     image: mysql:8    
#     restart: always
#     environment:
#       - MYSQL_DATABASE=book_example
#       - MYSQL_USER=root
#       - MYSQL_ROOT_PASSWORD=password
#     ports:
#       - '3306:3306'
#     volumes:
#       - ./db:/var/lib/mysql
#     networks:
#       - myapp


version: '3.8'

networks:
  myapp:
    driver: bridge

# docker run --name mysql -d     -p 3306:3306     -e MYSQL_ROOT_PASSWORD=password     --restart unless-stopped    mysql:8
services:
  db:
    image: mysql:8    
    container_name: database
    restart: always
    environment:
      - MYSQL_DATABASE=book_example
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - myapp
  myapp:
    build: .
    container_name: bookapp
    restart: always
    environment:
      - DB_DRIVER=mysql
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=book_example
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - '9000:9000'    
    depends_on:
      - db    
    networks: 
      - myapp


